### PR TITLE
Install .dll in prefix/bin

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Ok, I suppose this is valid only for Windows machines right?  Could you provide a patch that installs .DDL in `prefix/bin`  only on Windows?

**Comment by jschueller** [comment]
This applies for all win32 targets, ie not only on windows hosts, but also when cross-compiling from Linux to windows (eg mingw).

**Comment by FrancescAlted** [comment]
Yes, but my point is that your patch also affects to Unix machines, and probably this is not desired there, right?

**Comment by jschueller** [comment]
No, this does not affect unix machines, why would you assume that ?

**Comment by jschueller** [comment]
No, this does not affect unix machines, shared libraries are treated via the LIBRARY component (so installed into prefix/lib). On win32 this is different, dll is RUNTIME, and the import library is treated via ARCHIVE.

**Comment by FrancescAlted** [comment]
Ah, that makes more sense now.  Let me merge and see what's is happening on my Linux box.

**Comment by jschueller** [comment]
Not much will happen :)

**Comment by FrancescAlted** [comment]
Yup, seems to work as intended.  Thanks!

**Pull request merged**
