### PR TITLE
Inclusion request conan-center

### PR DESCRIPTION
**Pull request by lasote**
Hi Francesc, first of all, our apologies from the Conan team. We didn't measure or strength and your inclusion request to Conan center was not reviewed until now. We released the 1.0 version and increased the Conan team. So now we have some time to works with the community. We are very happy with the Conan adoption both in companies and OSS world, and we want your library in conan-center!

I've prepared this PR including Conan support:

- It is building and testing your library for more than a hundred different configurations: gcc, clang, apple-clang, mingw, Visual Studio, debug, release, shared, static, different libcxx.
- I modeled the testing (ctest) of your library in the recipe, so when CONAN_RUN_TESTS env variable is set, it will run the tests after build the library. I added it to the CI for the half of the configurations.
- Take a look to the `build.py`, that it is adjusting the version field to "dev" if there is no tag in appveyor/travis. You can adjust it if you want. A great new in Conan is that you don't need anymore to have the "version" field in the recipe, you can specify the complete reference in the "conan export" or "conan create" command.
- You can keep building your library as always, but if you want to try to pack it and testing just:
    `$ conan create . c-blosc/dev@francescalted/testing`

Your inclusion request will be accepted anyway because as the author of the library your request should have been accepted. So I hope you like this, tell me if you want any modification or if you don't want to be in conan-center anymore.

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Looks good to me.  Let's have it a try.  Thanks!

**Comment by lasote** [comment]
Hi!  I'm glad you like it

I saw that you CI is failing with the changes. Try to set the CONAN_PASSWORD in the travis/appveyor as a hidden variable with your bintray token (edit profiles / api key => show api key) and confirm that your login in bintray is "blosc" if don't please edit CONAN_LOGIN_USERNAME variable in the travis and appveyor yml files!

**Comment by FrancescAlted** [comment]
Yes, my CONAN_LOGIN_USERNAME is currently 'francescalted', although it would be a good idea to change it to 'blosc'.  With that, everything seems to build smoothly, and the setting the version field to 'dev' based on the existence of a tag is great.  That means that when as soon as I do a new release the c-blosc library will magically appear in conan central, right?

**Comment by lasote** [comment]
Great! 
I detected an issue in the **conan-package-tools** (already fixed),  it was uploading the `c-blosc/dev` version to your bintray repository. Now it should upload only when you tag something.
So, I tried the **v1.11.4b8** version and the Conanfile is not compatible with Conan 1.0 because of a little detail.  I can accept right now the inclusion request but we will be publishing to conan-center a dev package and a broken one :( definitely not the best debut.
I recommend removing the current versions in your remote repository (conan remove "*" -r myremote) and please ping me at **lasote@gmail.com** when you release a new version and I will accept in that moment the inclusion request. WDYT?

We would like also to write a microblog post showing your library, it looks very interesting. Do you have any planned date for the next release? Thanks!

**Pull request merged**
