### PR TITLE
tune macro in test_malloc for freebsd only

### PR DESCRIPTION
**Pull request by iblis17**
address https://github.com/Blosc/c-blosc/pull/188#discussion_r161681704

### CODE REVIEW

**Comment by iblis17** [comment]
well, no idea about the CI failure

**Comment by FrancescAlted** [comment]
Looks like Travis' Mac OSX service is not working correctly.  Will wait some more hours and will merge.

**Comment by iblis17** [comment]
the OSX build was cancelled ... by travis ? :/

**Comment by FrancescAlted** [comment]
Yeah, the OSX service is definitely broken at the moment.  Merging.

**Pull request merged**
