### PR TITLE
Correct the return code on too small compression buffers

### PR DESCRIPTION
**Pull request by kalvdans**
Fixes https://github.com/Blosc/c-blosc/issues/293

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Is it possible to include a cmake test for this?

**Comment by kalvdans** [comment]
> Is it possible to include a cmake test for this?

I modified the existing tests. Excellent test suite by the way!

**Comment by FrancescAlted** [comment]
LGTM.  BTW, the previous error condition (`sourcesize > BLOSC_MAX_BUFFERSIZE`) should return a 0 too.  Will do later on.

**Comment by FrancescAlted** [comment]
The new check `sourcesize > BLOSC_MAX_BUFFERSIZE` as well as initial support for `BLOSC_WARN` envvar is implemented in 403d50c.

**Comment by kalvdans** [comment]
Thanks Francesc for the quick response and fix! :)

**Pull request merged**
