### PR TITLE
Add GitHub Actions CI workflow for CMake.

### PR DESCRIPTION
**Pull request by nmoinvaz**
This PR adds GitHub Actions CI for CMake. It installs pre-requisite packages if needed, generates project files, and compiles them. Then it will run all the CMake tests.

AFAIK GitHub Actions shared runners support AVX2 so #138 may not be necessary.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
You should be able to remove both AppVeyor and Travis CI. I can include that in this PR if you want.

**Comment by nmoinvaz** [comment]
Here is an example of what the GitHub Actions CI looks like:
https://github.com/nmoinvaz/c-blosc/actions/runs/87089046

**Comment by FrancescAlted** [comment]
Looks really good to me.  I like the variety of scenarios that you are testing, specially SSE2/AVX2 deactivation and the possibility to link (or not) with external codecs.  I think I am going to merge and deactivate TravisCI and AppVeyor promptly.  Thank you!

**Comment by nmoinvaz** [comment]
Thanks! I will do one for c-blosc2 next.

**Comment by nmoinvaz** [comment]
For some reason AppVeyor is still showing up for the checks for this project.
image

https://ci.appveyor.com/project/FrancescAlted/c-blosc/builds/32449492

**Comment by FrancescAlted** [comment]
Good point.  I deactivated the webhooks for AppVeyor and TravisCI.  This should fix it.

**Pull request merged**
