### PR TITLE
cmake coveralls

### PR DESCRIPTION
**Pull request by FrancescElies**
Hi,

I was playing around with coveralls and I saw https://github.com/JoakimSoderberg/coveralls-cmake, might you be interested in having coveralls for c-blosc too?

If you find this doesn't apply, please feel free to close this PR, in case you think this might be useful it still needs some stuff to be done.

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Absolutely interested :)

Enviat des del meu iPhone

El 01/09/2015, a les 18:12, Francesc Elies <notifications@github.com> va escriure:

**Comment by FrancescElies** [comment]
I believe the DEBUG flag makes tests last 20x times longer and travis believes something is broken due to inactivity.

For example: 
- In release mode takes 1470/1479 Test #1470: test_lz4_shuffle_n ...........................   Passed    3.98 sec
- In debug mode takes  1470/1479 Test #1470: test_lz4_shuffle_n ...........................   Passed  374.25 sec

**Comment by FrancescAlted** [comment]
Uh oh, a 20x slowdown is not fun.  Unless a workaround can be found, I think that could be a show stopper :(  But thanks for trying anyway :)

**Comment by FrancescElies** [comment]
only affects one of the jobs on a travis build, but still not great :/.
Shall I close and if I find a workaround reopen & report back?

**Comment by FrancescAlted** [comment]
Yes, the problem is that for slow compressors (lz4hc and zlib), the job takes too much time (> 10 min) and Travis aborts it:

```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

So, I think it makes little sense to continue with this. So yeah, please close this and feel free to re-open in case you can find a solution.

**Pull request closed without merging**
