### PR TITLE
Simplified version of appveyor config

### PR DESCRIPTION
**Pull request by FrancescAlted**
This tries to get rid of the Conan stuff, as it takes too much time to be processed.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Have you thought about moving to GitHub Actions CI?

**Comment by FrancescAlted** [comment]
Yeah, that would be a good move indeed, specially now that the Blosc project has been upgraded to a Team plan.  Would you like to propose a PR for this?

**Comment by nmoinvaz** [comment]
Sure. Do you recommend new develop on c-blosc or c-blosc2?

**Comment by FrancescAlted** [comment]
Well, using GitHub Actions in both c-blosc and c-blosc2 would be cool, but it all depends on your job queue ;-)

**Comment by FrancescAlted** [comment]
After the new support for Actions, this is obsolote and not needed anymore.  Closing.

**Pull request closed without merging**
