### PR TITLE
AVX2 version shuffle and unshuffle

### PR DESCRIPTION
**Pull request by littlezhou**
The first commit is the implementation of AVX2 functions  and some changes have been made in order to make it work properly. The second commit adds a standalone testing, it compares the the time need to shuffle/unshuffle for AVX2 and SSE2.

### CODE REVIEW

**Comment by esc** [comment]
yes, shuffle isn't the bottleneck, but still!

**Comment by FrancescAlted** [comment]
Hey this is really nice work.  I was meaning doing this for long time, but never had the chance before.  Travis is saying that probably the cmake files still need some love, but this is a great start.  Thanks for sharing!

**Comment by littlezhou** [comment]
Thanks for your appreciation! The cmake files has been modified and a pull request has been create,  but i don't know whether it is send out successfully due to the bad network...

**Comment by esc** [comment]
It recently occurred to me that this will be relevant when we start to 'multishuffle'.

**Comment by FrancescAlted** [comment]
:+1:

Enviat des del meu iPhone

El 05/04/2015, a les 19:52, Valentin Haenel <notifications@github.com> va escriure:

**Comment by FrancescAlted** [comment]
Hey @littlezhou I would like to merge this, but unfortunately master has changed and I cannot merge easily.  Could you rebase your branch on master please?

**Comment by littlezhou** [comment]
Ok, a pull request has been created for you to review.

**Comment by FrancescAlted** [comment]
Well, I just wanted a *git rebase* of the existing PR, but don't worry, let me mark that the new PR will superseed this.

**Comment by FrancescAlted** [comment]
Superseded by #99.

**Pull request closed without merging**
